In [1]:
import numpy as np

# Numpy
- C 언어로 구현된 파이썬 라이브러리로써, 고성능의 수치 계산을 위해 만들어짐
- 벡터 및 행렬 연산에 있어서 편리한 기능 제공
- 다차원 배열 객체 지원
- 데이터에 대한 빠른 연산 가능
- pandas 와 matplotlib의 기반으로 사용

### ndarray 생성

In [6]:
list1 = [0, 1, 2, 3, 4]
arr1 = np.array(list1)
print(arr1)
print(type(arr1))

list2 = [[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]]
arr2 = np.array(list2)
print(arr2)
print(type(arr2))

[0 1 2 3 4]
<class 'numpy.ndarray'>
[[0 1 2 3 4]
 [5 6 7 8 9]]
<class 'numpy.ndarray'>


In [47]:
#랜덤값으로 배열 생성(난수생성)
data = np.random.randn(2, 3) # 2행 3열
print(data)
print("max of arr:", np.max(data))
print("min of arr:", np.min(data))

[[ 2.23365916 -0.25939901  1.46120211]
 [ 0.55995843  0.29198512  0.48993117]]
max of arr: 2.2336591587148713
min of arr: -0.25939901278044103


In [7]:
# 초기화된 배열도 생성가능
arr = np.zeros([3,4])
print(arr.shape)
print(arr)

(3, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
# 초기화된 배열도 생성가능
arr = np.ones([3,4])
print(arr.shape)
print(arr)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### ndarray의 타입, 크기, 차원

In [9]:
print("type : ", arr.dtype)
print("shape : ", arr.shape)
print("rank : ", arr.ndim)

type :  float64
shape :  (3, 4)
rank :  2


In [13]:
arr = np.reshape(arr, [2, 6])
print(arr)
print(arr.shape)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
(2, 6)


# ndarray의 연산

In [14]:
print(arr)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [15]:
# arr + 1
print(arr + 1)

[[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]


In [17]:
# arr x 5
print(arr * 5)

[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [19]:
# arr / 2
print(arr / 2)

[[0.5 0.5 0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5 0.5 0.5]]


## Broadcasting : important!!
![nn](https://paris-swc.github.io/advanced-numpy-lesson/fig/numpy_broadcasting.png)

In [20]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([10,11,12])
print(arr1+arr2)

[[11 13 15]
 [14 16 18]]


# indexing

## (1) Indexing

In [21]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [22]:
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
print("1행 : ", arr[0])
print("2행 : ", arr[1])

1행 :  [1 2 3 4]
2행 :  [5 6 7 8]


In [30]:
print("1열 : ", arr[:,0])
print("2열 : ", arr[:,1])

1열 :  [1 5 9]
2열 :  [ 2  6 10]


In [25]:
print("1행 1열 : ", arr[0,0])
print("2행 2열 : ", arr[1,1])
print("3행 3열 : ", arr[2,2])

1행 1열 :  1
2행 2열 :  6
3행 3열 :  11


In [44]:
# Boolean indexing
print(arr)
print(arr > 3)
print("boolean indexing :", arr[arr>3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]]
boolean indexing : [ 4  5  6  7  8  9 10 11 12]


## (2) Slicing

In [36]:
print(arr)
print(arr[:2, :3]) # 0,1행 + 0,1,2열로 slicing

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]
 [5 6 7]]
